# coding: utf-8

"""
    Auction API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import nordpool_client
from nordpool_client.models.blockorders_order_id_body import BlockordersOrderIdBody  # noqa: E501
from nordpool_client.rest import ApiException


class TestBlockordersOrderIdBody(unittest.TestCase):
    """BlockordersOrderIdBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBlockordersOrderIdBody(self):
        """Test BlockordersOrderIdBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = nordpool_client.models.blockorders_order_id_body.BlockordersOrderIdBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
