# coding: utf-8

"""
    Auction API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import nordpool_client
from nordpool_client.models.connect_token_body import ConnectTokenBody  # noqa: E501
from nordpool_client.rest import ApiException


class TestConnectTokenBody(unittest.TestCase):
    """ConnectTokenBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConnectTokenBody(self):
        """Test ConnectTokenBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = nordpool_client.models.connect_token_body.ConnectTokenBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
