# coding: utf-8

"""
    Auction API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import nordpool_client
from nordpool_client.models.comment import Comment  # noqa: E501
from nordpool_client.rest import ApiException


class TestComment(unittest.TestCase):
    """Comment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComment(self):
        """Test Comment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = nordpool_client.models.comment.Comment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
