# coding: utf-8

"""
    Auction API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BlockordersOrderIdBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'blocks': 'list[Block]',
        'comment': 'Comment'
    }

    attribute_map = {
        'blocks': 'blocks',
        'comment': 'comment'
    }

    def __init__(self, blocks=None, comment=None):  # noqa: E501
        """BlockordersOrderIdBody - a model defined in Swagger"""  # noqa: E501
        self._blocks = None
        self._comment = None
        self.discriminator = None
        self.blocks = blocks
        if comment is not None:
            self.comment = comment

    @property
    def blocks(self):
        """Gets the blocks of this BlockordersOrderIdBody.  # noqa: E501

        A list of blocks which will have status \"Accepted\" in the new version of the block order. All active blocks in the previous version will be cancelled.  # noqa: E501

        :return: The blocks of this BlockordersOrderIdBody.  # noqa: E501
        :rtype: list[Block]
        """
        return self._blocks

    @blocks.setter
    def blocks(self, blocks):
        """Sets the blocks of this BlockordersOrderIdBody.

        A list of blocks which will have status \"Accepted\" in the new version of the block order. All active blocks in the previous version will be cancelled.  # noqa: E501

        :param blocks: The blocks of this BlockordersOrderIdBody.  # noqa: E501
        :type: list[Block]
        """
        if blocks is None:
            raise ValueError("Invalid value for `blocks`, must not be `None`")  # noqa: E501

        self._blocks = blocks

    @property
    def comment(self):
        """Gets the comment of this BlockordersOrderIdBody.  # noqa: E501


        :return: The comment of this BlockordersOrderIdBody.  # noqa: E501
        :rtype: Comment
        """
        return self._comment

    @comment.setter
    def comment(self, comment):
        """Sets the comment of this BlockordersOrderIdBody.


        :param comment: The comment of this BlockordersOrderIdBody.  # noqa: E501
        :type: Comment
        """

        self._comment = comment

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BlockordersOrderIdBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BlockordersOrderIdBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
