# coding: utf-8

"""
    Auction API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConnectTokenBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'grant_type': 'str',
        'scope': 'str',
        'username': 'str',
        'password': 'str'
    }

    attribute_map = {
        'grant_type': 'grant_type',
        'scope': 'scope',
        'username': 'username',
        'password': 'password'
    }

    def __init__(self, grant_type=None, scope=None, username=None, password=None):  # noqa: E501
        """ConnectTokenBody - a model defined in Swagger"""  # noqa: E501
        self._grant_type = None
        self._scope = None
        self._username = None
        self._password = None
        self.discriminator = None
        if grant_type is not None:
            self.grant_type = grant_type
        if scope is not None:
            self.scope = scope
        if username is not None:
            self.username = username
        if password is not None:
            self.password = password

    @property
    def grant_type(self):
        """Gets the grant_type of this ConnectTokenBody.  # noqa: E501


        :return: The grant_type of this ConnectTokenBody.  # noqa: E501
        :rtype: str
        """
        return self._grant_type

    @grant_type.setter
    def grant_type(self, grant_type):
        """Sets the grant_type of this ConnectTokenBody.


        :param grant_type: The grant_type of this ConnectTokenBody.  # noqa: E501
        :type: str
        """

        self._grant_type = grant_type

    @property
    def scope(self):
        """Gets the scope of this ConnectTokenBody.  # noqa: E501


        :return: The scope of this ConnectTokenBody.  # noqa: E501
        :rtype: str
        """
        return self._scope

    @scope.setter
    def scope(self, scope):
        """Sets the scope of this ConnectTokenBody.


        :param scope: The scope of this ConnectTokenBody.  # noqa: E501
        :type: str
        """

        self._scope = scope

    @property
    def username(self):
        """Gets the username of this ConnectTokenBody.  # noqa: E501


        :return: The username of this ConnectTokenBody.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this ConnectTokenBody.


        :param username: The username of this ConnectTokenBody.  # noqa: E501
        :type: str
        """

        self._username = username

    @property
    def password(self):
        """Gets the password of this ConnectTokenBody.  # noqa: E501


        :return: The password of this ConnectTokenBody.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this ConnectTokenBody.


        :param password: The password of this ConnectTokenBody.  # noqa: E501
        :type: str
        """

        self._password = password

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConnectTokenBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConnectTokenBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
