# coding: utf-8

"""
    Auction API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CurveordersOrderIdBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'comment': 'Comment',
        'curves': 'list[Curve]'
    }

    attribute_map = {
        'comment': 'comment',
        'curves': 'curves'
    }

    def __init__(self, comment=None, curves=None):  # noqa: E501
        """CurveordersOrderIdBody - a model defined in Swagger"""  # noqa: E501
        self._comment = None
        self._curves = None
        self.discriminator = None
        if comment is not None:
            self.comment = comment
        self.curves = curves

    @property
    def comment(self):
        """Gets the comment of this CurveordersOrderIdBody.  # noqa: E501


        :return: The comment of this CurveordersOrderIdBody.  # noqa: E501
        :rtype: Comment
        """
        return self._comment

    @comment.setter
    def comment(self, comment):
        """Sets the comment of this CurveordersOrderIdBody.


        :param comment: The comment of this CurveordersOrderIdBody.  # noqa: E501
        :type: Comment
        """

        self._comment = comment

    @property
    def curves(self):
        """Gets the curves of this CurveordersOrderIdBody.  # noqa: E501

        Array of curve objects  # noqa: E501

        :return: The curves of this CurveordersOrderIdBody.  # noqa: E501
        :rtype: list[Curve]
        """
        return self._curves

    @curves.setter
    def curves(self, curves):
        """Sets the curves of this CurveordersOrderIdBody.

        Array of curve objects  # noqa: E501

        :param curves: The curves of this CurveordersOrderIdBody.  # noqa: E501
        :type: list[Curve]
        """
        if curves is None:
            raise ValueError("Invalid value for `curves`, must not be `None`")  # noqa: E501

        self._curves = curves

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CurveordersOrderIdBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CurveordersOrderIdBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
