# coding: utf-8

"""
    Auction API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Period(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'contract_id': 'str',
        'volume': 'float'
    }

    attribute_map = {
        'contract_id': 'contractId',
        'volume': 'volume'
    }

    def __init__(self, contract_id=None, volume=None):  # noqa: E501
        """Period - a model defined in Swagger"""  # noqa: E501
        self._contract_id = None
        self._volume = None
        self.discriminator = None
        if contract_id is not None:
            self.contract_id = contract_id
        if volume is not None:
            self.volume = volume

    @property
    def contract_id(self):
        """Gets the contract_id of this Period.  # noqa: E501

        Contract id.  # noqa: E501

        :return: The contract_id of this Period.  # noqa: E501
        :rtype: str
        """
        return self._contract_id

    @contract_id.setter
    def contract_id(self, contract_id):
        """Sets the contract_id of this Period.

        Contract id.  # noqa: E501

        :param contract_id: The contract_id of this Period.  # noqa: E501
        :type: str
        """

        self._contract_id = contract_id

    @property
    def volume(self):
        """Gets the volume of this Period.  # noqa: E501

        Block volume in MW.  # noqa: E501

        :return: The volume of this Period.  # noqa: E501
        :rtype: float
        """
        return self._volume

    @volume.setter
    def volume(self, volume):
        """Sets the volume of this Period.

        Block volume in MW.  # noqa: E501

        :param volume: The volume of this Period.  # noqa: E501
        :type: float
        """

        self._volume = volume

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Period, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Period):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
